frase = 'Curso em Video Python'
print(frase)
print(frase[3])
print(frase[3:13])
print(frase[13:])
print(frase[1:15:2])
print(frase.count('o'))
print(frase.upper().count('o'))
print(frase.lower().find('video'))
print(len(frase))
print(len(frase.strip()))
print(frase.replace('Python', 'Android'))
print('Curso' in frase)
print(frase.find('Video'))
print(frase.lower())
print(frase.upper())
print(frase.capitalize())
print(frase.title())
print(frase.strip())
print(frase.rstrip())
print(frase.lstrip())
print(frase.split())

print('-'.join(frase))


