num = int(input('Digite um número e veja sua tabuada: '))
print('O número {} x 1 é: {}'.format(num, num*1))
print('O número {} x 2 é: {}'.format(num, num*2))
print('O número {} x 3 é: {}'.format(num, num*3))
print('O número {} x 4 é: {}'.format(num, num*4))
print('O número {} x 5 é: {}'.format(num, num*5))
print('O número {} x 6 é: {}'.format(num, num*6))
print('O número {} x 7 é: {}'.format(num, num*7))
print('O número {} x 8 é: {}'.format(num, num*8))
print('O número {} x 9 é: {}'.format(num, num*9))
print('O número {} x 10 é: {}'.format(num, num*10))
